<?php
namespace backend\models;

use yii\base\Model;

class Edit extends Model{
    public $password;
    public $password_x;
    public $password_s;

    public function rules()
    {
        return [
            [['password','password_x','password_s'],'required'],
            //liangci兩次密碼必須一致
            ['password_s','compare','compareAttribute'=>'password_x'],
            //yanzheng jiu mima
            ['password','validatePw'],
        ];
        //return parent::rules(); // TODO: Change the autogenerated stub
    }

    /*public function attributeLabels()
    {
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }*/

    public function attributeLabels()
    {
        return [

            'password' => '密码',
            'password_x'=>'新密码',
            'password_s'=>'确认新密码',

        ];
    }
    public function validatePw(){
        $admin =  \Yii::$app->user->identity;
        if(!\Yii::$app->security->validatePassword($this->password,$admin->password_hash)){
            $this->addError('password','旧密碼不正確');
        }
    }
    public function changePw(){

        $admin =  \Yii::$app->user->identity;
        $admin->password_hash=\Yii::$app->security->generatePasswordHash($this->password_x);
                return $admin->save();
    }

}